### ISSUE TITLE
RC5 introduce a state bug

### ISSUE THREAD

**Issue by Tolriq** [Syer10/voyager#2]
So this is quite strange and I have not yet debug it reporting first in case there's something obvious.

Now when I switch tabs with my custom tab navigator that keep the tabs states the state is lost on the first switch but not on the future ones.

Like I'm on tab A and scroll down, go to tab B, return to tab A, the screen is reset at top. Do the same again and all future cases do properly keep state, like something is not initialized on first instance creation.

Edit: So confirmed it was added in RC5, will try to figure out, but I hate AS not supporting multiplatform composite builds :(

**Comment by Syer10** [comment]
Huh, that is some weird behavior. I'm not sure how that could have popped up though, the differences between RC4 and RC5 related to tab states is pretty much nothing. Did you possibly combine AndroidScreen and the Tab interface?

**Comment by Tolriq** [comment]
Ha yes my tabs are AndroidScreen to support hilt. In all case I'll try to debug next week, just wondering if there was some obvious changes that I should look after for the repro.

**Comment by Syer10** [comment]
Then its probably related to the changes I did for SavedStateHandle, maybe see if `ScreenLifecycle.onCreate` and `ScreenLifecycle.performSave` in the LifecycleDisposableEffect is firing correctly. Or maybe somehow navigator.onDispose is firing at some point for some reason. 

Since your talking about scroll progress though it shouldnt be related to SavedStateHandle in the first place since that is stored in the lifecycle SaveableState and not the screen one. Im not sure how it would be caused then.

**Comment by Tolriq** [comment]
Ok thanks, will enjoy again the pain to debug without composite build support :(

**Comment by michaldrabik** [comment]
Can confirm the same behaviour @Tolriq described happens in my case with tabs.

**Comment by Tolriq** [comment]
Sorry I completely lack time to try to debug that one for the moment :( Too many things to do and not enough time.

**Comment by Tolriq** [comment]
Still lack time to fully debug :( 

Usage is with:
```kotlin
Navigator(tab, disposeBehavior = NavigatorDisposeBehavior(disposeNestedNavigators = false, disposeSteps = false), onBackPressed = null) { navigator ->
```

Then in a tab: `val lazyGridState = rememberLazyGridState()` will no more work when changing tabs. (Still properly works when navigating down then up in the child navigator).

When logging the disposable of the viewmodels nothing seems to be disposed, seems there's some mismatch in data somewhere that break states, probably a side effect of the staved state https://github.com/Syer10/voyager/commit/cc1fcf206f8962e65d97e74d0e92c855972b1cd1 or a race and side effect of https://github.com/Syer10/voyager/commit/e4440e6d435e79bbd5737d23ac4134cc87b46e5e

**Comment by Syer10** [comment]
I'm back to using the main version of Voyager, I am closing all issues because of this.
